### ISSUE TITLE
Use Black and isort for automatic formatting

### ISSUE THREAD

**Issue by felix-hilden** [felix-hilden/tekore#184]
We should format code automatically. I already tried out a configuration in #183, but due to some issues with Black (psf/black#1054 & psf/black#1288) we'll be delaying that.

Here's the configuration in `tox.ini`:

```
[flake8]
select = C,E,F,W,B,B9
ignore = B305,E203,E402,E501,E722,F401,W503

[isort]
line_length=88
use_parentheses=True
multi_line_output=3
lines_between_types=1
include_trailing_comma=True
known_third_party=requests,httpx
known_first_party=tekore
force_grid_wrap=0

[testenv:black-run]
description = Run Black formatting on code
whitelist_externals = black
commands = black --target-version py36 .

[testenv:black-check]
description = Check code formatting
whitelist_externals = black
commands = black --target-version py36 --check .

[testenv:isort-run]
description = Run isort formatting on imports
whitelist_externals = isort
commands = isort -y

[testenv:isort-check]
description = Check import formatting
whitelist_externals = isort
commands = isort --check-only

[testenv:format]
description = Run all code formatting
whitelist_externals =
    isort
    black
commands =
    isort -y
    black --target-version py36 .
```

**Comment by ichard26** [comment]
Hello, Black contributor here! FYI, isort 5 [has been released](https://timothycrosley.github.io/isort/docs/major_releases/introducing_isort_5/). It now has a built-in Black profile support via `profile=black` so the configuration can be simplified. Also isort 5 fixes another incompatiblity issue with Black (https://github.com/psf/black/issues/251). isort 5 does require CPython 3.6.0+ to run, but it appears that this project targets 3.6.0+ already :tada: 

https://github.com/felix-hilden/tekore/blob/31166a10f712a42e65db2171f6994a58871410f1/setup.py#L3

Just something to keep in mind when considering to use Black (and isort) together for automatic code formatting. We're still working on the "magic trailing comma" issues so I do agree that introducing Black should wait for now (probably isort too since v5 is big change and probably needs a bit of ironing out - if isort v5 is used).

**Comment by felix-hilden** [comment]
Thank you for the information and suggestions!

**Comment by felix-hilden** [comment]
Let's wait just a bit for the stable version of Black to be released. I was a bit quick to pull off the label.

**Comment by felix-hilden** [comment]
Also, when the time comes, Pre-commit could be used to enforce the formatting and reducing the number of oopsies. Remembering to run `tox -e format` before committing is just a worse version of having Pre-commit. Black uses it, so we could use that configuration at least as a basis for us.

**Comment by felix-hilden** [comment]
We could also use some RST formatter if one exists. Prettier is only for MD.

**Comment by Senpos** [comment]
> Let's wait just a bit for the stable version of Black to be released. I was a bit quick to pull off the label.

The first stable version of Black released! 🎉
https://github.com/psf/black/blob/main/CHANGES.md#2210

**Comment by felix-hilden** [comment]
😉 Thanks for the reminder!

**Comment by felix-hilden** [comment]
Finally there's enough action to warrant a resolution here, I'll look to introduce this for 5.0
