### ISSUE TITLE
Help for "event_change"

### ISSUE THREAD

**Issue by KSuondProject** [felix-hilden/tekore#248]
Hi all,

Can someone help me to write a simple python code for retrieve a way for change a variable when the player start/change/resume/stop the reproduction?

I've made something like this for the "change" state but I'm not a champ with python code...
The idea is that the function compare a first variable with a prev title and wait 15 secs to read another variable with the current title; if the 2 variables are different a boolean variable is set up.
This code works but sometimes it can't see the difference between the 2 songs if the change is too close with the expire of the time.sleep...

Thanks in advance for the help!

```
def refresh(refresh_now):
    conf = tk.config_from_file(file, return_refresh=True)
    token = tk.refresh_user_token(*conf[:2], conf[3])
    spotify = tk.Spotify(token)

    with spotify.token_as(token):
        p1 = spotify.playback()       
    curr_song = []
    prev_song = [] 
    if p1 is not None:
        if p1.is_playing is not False:            
            prev_song = p1.item.name
            print("previous song " + prev_song)
            time.sleep(15.0)
            p2 = spotify.playback()
            if p2 is not None: 
                if p2.is_playing is not False:
                    curr_song = p2.item.name
                    print("current song "+ curr_song)
                    time.sleep(1.0)   
    if prev_song != curr_song:
        refresh_now = True      
        print("refresh command received")
        return refresh_now
```

**Comment by felix-hilden** [comment]
Hey!

You'd most likely want to just use one variable as the current song and another for the previous known song. Also, the decisions of returning true or false might depend on your needs. So change the code below to fit yours. If I may write some pseudo code:

```python
previous = playback()
sleep(15)
current = playback()

if previous is None or current is None:
    return False # or True?

if not current.is_playing:
    return False # or True?

# some other combination checks here?

# finally the most important check
if previous.item.name == current.item.name:
    return False
else:
    return True
```

Yeah the web API can be a bit slow when it comes to updating playback. That's a pain. But I hope this helps. You're on the right track. And if it works already then perfect! Improvements on working code are a different beast altogether from just debugging.

That being said, I don't think this is an enhancement to the library. It would be more appropriate to ask for help on our Discord or in Stack Overflow than on GitHub, since this is not development related. Both links are available in the issue creation screen. So I'll close this issue and hope to see you there! Much appreciated!
