### ISSUE TITLE
Compiling .exe programs with import tekore not functioning

### ISSUE THREAD

**Issue by ChocolateEinstein** [felix-hilden/tekore#284]
### Issue
When compiling any .py file with [PyInstaller 5.7.0](https://pypi.org/project/pyinstaller/) and [python 3.11](https://www.python.org/) on a windows 10 machine, an .exe program will be successfully compiled, but it will not function, throwing the error:
`PS C:\Users\osita\Documents\VRCOSCBPM\dist> .\HelloWorld.exe
Traceback (most recent call last):`
`  File "HelloWorld.py", line 1, in <module>`
`  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load`
`  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked`
`  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked`
`  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module`
`  File "tekore\__init__.py", line 75, in <module>`
`  File "tekore\_start.py", line 35, in read_version_file`
`  File "pathlib.py", line 1058, in read_text`
`  File "pathlib.py", line 1044, in open`
`FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\osita\\AppData\\Local\\Temp\\_MEI169882\\tekore\\VERSION'
[28044] Failed to execute script 'HelloWorld' due to unhandled exception!`

### Expected behavior
The program should just run as a .exe, assuming there are no issues with the .py file it's based on.

### Steps to reproduce
Create a HelloWorld.py with the contents 
`import tekore`

`print('Hello World')`
`input()`
Then try to build it with PyInstaller, eg `pyinstaller --onefile HelloWorld.py`

### Possible solution
Commenting out the line `__version__ = _read_version_file()` from \tekore\__init__.py\, line 75, has resulted in successful .exe programs compiling on my machine

**Comment by felix-hilden** [comment]
Hi! Tekore is (or rather was until very recently) packaged with a VERSION file that carries the current library version and is read on import as you've found. Since, based on our chat on Discord, you can import `tekore` in a script just fine this is more likely an issue with Pyinstaller or its usage. Unfortunately I don't have experience with it. Perhaps `--add-data` ([doc](https://pyinstaller.org/en/stable/runtime-information.html?highlight=use-data#placing-data-files-at-expected-locations-inside-the-bundle)) or `--one-dir` instead of `--one-file` would work.

But as I said, the VERSION file was recently removed when I did some tooling upgrades, so this issue is unlikely to occur in future releases! You can reinstall Tekore via git to get the bleeding edge:

```sh
pip install git+https://github.com/felix-hilden/tekore.git
```

**Comment by felix-hilden** [comment]
I'll close this issue as fixed at least in the most recent releases. There's not much else we can do. Let me know if you have any issues with the latest release though!
