### ISSUE TITLE
Document restricted endpoints

### ISSUE THREAD

**Issue by felix-hilden** [felix-hilden/tekore#331]
Spotify recently removed a bunch of endpoints for new apps. We should document them as restricted and make sure tests still pass. https://developer.spotify.com/blog/2024-11-27-changes-to-the-web-api

**Comment by Ch00k** [comment]
My app started failing to list my playlists, which I traced down to the fact that `followed_playlists` is now returning `None` values along with `SimplePlaylist` objects, which `SimplePlaylistPaging` allows (`items: List[Optional[SimplePlaylist]]`). The `None` values are there, most likely` due to point number 8 from the above mentioned blog post.

In this particular case the code is technically correct, because it allows `None` values in the list.

**Comment by felix-hilden** [comment]
Yeah it might have become more common! The change was added already when we moved to pydantic a while back (although the specific reason escapes my mind) but you encountering it might indeed be due to the recent changes.

**Comment by felix-hilden** [comment]
Tests still pass BTW, probably my test app was not in development mode anymore.
