### ISSUE TITLE
Using maximum limits automatically

### ISSUE THREAD

**Issue by ghost** [felix-hilden/tekore#66]
.. for reducing needed api calls and speeding up thing

**Comment by bugflush** [comment]
Current defaults seems copied what api defines as default. They are very small and the maximums are not very large either.

for example categories default limit is now 20, maximum is 50. And api currently returns total categories over 20 but less than 50.

**Comment by bugflush** [comment]
also quite inconsistent:
... album().tracks.limit -> 50 ... but album_tracks() uses limit 20

**Comment by felix-hilden** [comment]
I'd hate to change it precisely because it is the API default too. I agree it would speed up calls to lengthy resources. But for any such call it's easy to include the maximum limit.

`tracks = s.all_items(s.album_tracks(album_id, limit=50))`

Many times all items are not needed, and 20 might be fine. I think we'll be lads to the people over at Spotify and reduce their load a bit, or respect whatever their reason was for these defaults.

**Comment by marioortizmanero** [comment]
I'm afraid OP deleted his account, I didn't know about @ghost :(

If you need someone's else opinion, I'd leave the default limits as they are too. It's really easy to modify anyway, as you pointed out.

**Comment by felix-hilden** [comment]
Yeah, I noticed, too bad. But I'll close this then, as some sort of consensus has been achieved.

**Comment by felix-hilden** [comment]
This should be revisited. It wouldn't be too hard to provide a parameter / context manager to turn on maximum limits.
